### ISSUE TITLE
how do i stop it

### ISSUE THREAD

**Issue by jmxamongusmodder** [SergeyMC9730/roulette#5]
how do i stop it

**Comment by jmxamongusmodder** [comment]
i cant press the stop roulette button cuz my mouse is always hidden unless in pause menu
and no keybinds work
help!!

**Comment by SergeyMC9730** [comment]
i think you need to make mouse unhidden

**Comment by jmxamongusmodder** [comment]
> i think you need to make mouse unhidden

well how do i do that

**Comment by SergeyMC9730** [comment]
> > i think you need to make mouse unhidden
> 
> well how do i do that

![изображение](https://github.com/SergeyMC9730/roulette/assets/57207009/9b05b976-bbd5-408f-a516-a1e5db981dd2)
`Lock Cursor In-Game` should be disabled

**Comment by SergeyMC9730** [comment]
fixed in v1.1.0
