### ISSUE TITLE
Unable to click the button

### ISSUE THREAD

**Issue by RaijuV2** [SergeyMC9730/roulette#6]
Ive been having trouble figuring out how to click the button when it pops up, my mouse cursor doesn't appear and I cant move it at all. Is there a setting I need to fix in game or is there another way I can fix this?

**Comment by SergeyMC9730** [comment]
https://github.com/SergeyMC9730/roulette/issues/5#issuecomment-1935426587 you gotta do this

**Comment by Kbushra** [comment]
same problem here, cursor doesnt show up and cant click button

**Comment by SergeyMC9730** [comment]
fixed in v1.1.0
